# Generated by Django 3.2.5 on 2022-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='discription',
            field=models.CharField(max_length=300),
        ),
    ]
