# Generated by Django 3.2.5 on 2022-02-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='imgtopic',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
