# Generated by Django 4.0.2 on 2022-03-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_src',
            field=models.TextField(blank=True),
        ),
    ]
